import type { LevelDefinition } from "@lumaloop/level-schema";

export const world12Switchbacks: LevelDefinition[] = [
  {
    id: "world-12-level-01",
    name: "Bridge Key",
    world: "world-12-switchbacks",
    board: [
      { x: 0, y: 0, z: 0, kind: "SWITCH", toggleGroup: "amber" },
      { x: 0, y: 1, z: 0, kind: "NORMAL", toggleGroup: "amber", moveTo: { x: 1, y: 0, z: 0 } },
      { id: "goal-1", x: 2, y: 0, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["TOGGLE", "FORWARD", "ACTIVATE"],
    slotLimits: { main: 4 },
    stars: { one: 6, two: 5, three: 4 },
    metadata: {
      concept: "A switch can move a bridge tile into a missing path",
      designerNotes: "Use the familiar switch behavior: the bridge starts off the route and moves into the route when toggled.",
      idealSolutionLength: 4,
    },
  },
  {
    id: "world-12-level-02",
    name: "Two Bridges",
    world: "world-12-switchbacks",
    board: [
      { x: 0, y: 0, z: 0, kind: "SWITCH", toggleGroup: "amber" },
      { x: 0, y: 1, z: 0, kind: "NORMAL", toggleGroup: "amber", moveTo: { x: 1, y: 0, z: 0 } },
      { id: "goal-1", x: 2, y: 0, z: 0, kind: "TARGET" },
      { x: 3, y: 0, z: 0, kind: "SWITCH", toggleGroup: "violet" },
      { x: 3, y: 1, z: 0, kind: "NORMAL", toggleGroup: "violet", moveTo: { x: 4, y: 0, z: 0 } },
      { id: "goal-2", x: 5, y: 0, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["TOGGLE", "FORWARD", "ACTIVATE", "CALL_P1"],
    slotLimits: { main: 3, p1: 4 },
    stars: { one: 9, two: 8, three: 7 },
    metadata: {
      concept: "A helper can package the repeated switch-cross-light phase",
      designerNotes: "The reusable phrase starts on a switch: toggle, cross the moved bridge, and activate the target.",
      idealSolutionLength: 7,
    },
  },
  {
    id: "world-12-level-03",
    name: "Backtrack Bridge",
    world: "world-12-switchbacks",
    board: [
      { x: 0, y: 0, z: 0, kind: "SWITCH", toggleGroup: "amber" },
      { x: 0, y: 1, z: 0, kind: "NORMAL", toggleGroup: "amber", moveTo: { x: 1, y: 0, z: 0 } },
      { id: "goal-1", x: 2, y: 0, z: 0, kind: "TARGET" },
      { id: "goal-2", x: 0, y: 2, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["TOGGLE", "FORWARD", "TURN_LEFT", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 8, p1: 2, p2: 3 },
    stars: { one: 15, two: 14, three: 13 },
    metadata: {
      concept: "The same bridge opens the east path or the south path, so toggling back matters",
      designerNotes: "Use one helper for the two-step bridge crossing, and another helper to turn around and reuse it on the way back.",
      idealSolutionLength: 13,
    },
  },
  {
    id: "world-12-level-04",
    name: "Recursive Switchback",
    world: "world-12-switchbacks",
    board: [
      { x: 0, y: 0, z: 0, kind: "SWITCH", toggleGroup: "amber" },
      { x: 0, y: 1, z: 0, kind: "NORMAL", toggleGroup: "amber", moveTo: { x: 1, y: 0, z: 0 } },
      { id: "goal-1", x: 2, y: 0, z: 0, kind: "TARGET" },
      { x: 0, y: 2, z: 0, kind: "SWITCH", toggleGroup: "violet" },
      { x: 0, y: 3, z: 0, kind: "NORMAL", toggleGroup: "violet", moveTo: { x: 1, y: 2, z: 0 } },
      { id: "goal-2", x: 2, y: 2, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["TOGGLE", "FORWARD", "TURN_LEFT", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 1, p1: 11, p2: 2 },
    stars: { one: 16, two: 15, three: 14 },
    metadata: {
      concept: "A recursive routine can repeat the switchback pattern until the final target ends the run",
      designerNotes: "The recursive routine should call a small crossing helper several times instead of spelling out each two-step bridge segment.",
      idealSolutionLength: 14,
    },
  },
  {
    id: "world-12-level-05",
    name: "Raised Switchback",
    world: "world-12-switchbacks",
    board: [
      { x: 0, y: 0, z: 0, kind: "SWITCH", toggleGroup: "amber" },
      { x: 0, y: 1, z: 0, kind: "NORMAL", toggleGroup: "amber", moveTo: { x: 1, y: 0, z: 0 } },
      { id: "goal-1", x: 2, y: 0, z: 1, kind: "TARGET" },
      { id: "goal-2", x: 0, y: 2, z: 1, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["TOGGLE", "FORWARD", "TURN_LEFT", "JUMP", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 6, p1: 3, p2: 4 },
    stars: { one: 15, two: 14, three: 13 },
    metadata: {
      concept: "The switchback pattern gets harder when returning from the side branch requires a legal descent",
      designerNotes: "Package the climb-and-light phrase and the turn-around descent. The main routine should describe phases, not every step.",
      idealSolutionLength: 13,
    },
  },
];
