import type { LevelDefinition } from "@lumaloop/level-schema";

export const world04Procedures: LevelDefinition[] = [
  {
    id: "world-04-level-01",
    name: "Twin March",
    world: "world-04-procedures",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { x: 2, y: 0, z: 0, kind: "NORMAL" },
      { x: 3, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 4, y: 0, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "ACTIVATE", "CALL_P1"],
    slotLimits: { main: 3, p1: 2 },
    stars: { one: 7, two: 6, three: 5 },
    metadata: {
      concept: "Use a procedure instead of repeating the same walk block",
      designerNotes: "There is a repeated walk chunk here. The puzzle is deciding where to store it.",
      idealSolutionLength: 5,
    },
  },
  {
    id: "world-04-level-02",
    name: "Nested Corner",
    world: "world-04-procedures",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { x: 2, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 1, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_RIGHT", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 3, p1: 2, p2: 2 },
    stars: { one: 8, two: 7, three: 7 },
    metadata: {
      concept: "Functions can call other functions to compress a route",
      designerNotes: "One helper can own the distance; another can own the corner.",
      idealSolutionLength: 7,
    },
  },
  {
    id: "world-04-level-03",
    name: "Signal Line",
    world: "world-04-procedures",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { id: "goal-2", x: 1, y: 0, z: 0, kind: "TARGET" },
      { id: "goal-3", x: 2, y: 0, z: 0, kind: "TARGET" },
      { id: "goal-4", x: 3, y: 0, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "ACTIVATE", "CALL_P1"],
    slotLimits: { main: 4, p1: 2 },
    stars: { one: 8, two: 7, three: 6 },
    metadata: {
      concept: "A procedure can package a repeated action pair, not just movement",
      designerNotes: "Package the repeated action pair, not just the repeated movement.",
      idealSolutionLength: 6,
    },
  },
  {
    id: "world-04-level-04",
    name: "Stair Pair",
    world: "world-04-procedures",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 0, z: 0, kind: "TARGET" },
      { x: 2, y: -1, z: 0, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: -2, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_LEFT", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 4, p1: 2, p2: 2 },
    stars: { one: 10, two: 9, three: 8 },
    metadata: {
      concept: "Nested procedures can reuse a movement chunk after changing orientation",
      designerNotes: "Reuse the same straight segment from more than one orientation.",
      idealSolutionLength: 8,
    },
  },
  {
    id: "world-04-level-05",
    name: "Spiral Signals",
    world: "world-04-procedures",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 0, z: 0, kind: "TARGET" },
      { x: 2, y: -1, z: 0, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: -2, z: 0, kind: "TARGET" },
      { x: 1, y: -2, z: 0, kind: "NORMAL" },
      { id: "goal-3", x: 0, y: -2, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_LEFT", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 4, p1: 2, p2: 3 },
    stars: { one: 11, two: 10, three: 9 },
    metadata: {
      concept: "Build one reusable macro out of another to compress a repeating corner pattern",
      designerNotes: "Look for a corner-shaped chunk that repeats, not a single repeated command.",
      idealSolutionLength: 9,
    },
  },
  {
    id: "world-04-level-06",
    name: "Lift Rhythm",
    world: "world-04-procedures",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 1, y: 0, z: 1, kind: "TARGET" },
      { x: 2, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-2", x: 3, y: 0, z: 1, kind: "TARGET" },
      { x: 4, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-3", x: 5, y: 0, z: 1, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["JUMP", "ACTIVATE", "CALL_P1"],
    slotLimits: { main: 3, p1: 3 },
    stars: { one: 8, two: 7, three: 6 },
    metadata: {
      concept: "Procedures still matter when the repeated motif is about height, not distance",
      designerNotes: "The repeated idea here is a height rhythm, not a path shape.",
      idealSolutionLength: 6,
    },
  },
];
