import type { LevelDefinition } from "@lumaloop/level-schema";

export const world07VeryHard: LevelDefinition[] = [
  {
    id: "world-07-level-01",
    name: "Helix Corners",
    world: "world-07-very-hard",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 1, z: 1, kind: "NORMAL" },
      { id: "goal-2", x: 1, y: 2, z: 1, kind: "TARGET" },
      { x: 1, y: 3, z: 1, kind: "NORMAL" },
      { x: 0, y: 3, z: 2, kind: "NORMAL" },
      { id: "goal-3", x: -1, y: 3, z: 2, kind: "TARGET" },
      { x: -2, y: 3, z: 2, kind: "NORMAL" },
      { x: -2, y: 2, z: 3, kind: "NORMAL" },
      { id: "goal-4", x: -2, y: 1, z: 3, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_RIGHT", "JUMP", "ACTIVATE", "CALL_P1"],
    slotLimits: { main: 1, p1: 6 },
    stars: { one: 9, two: 8, three: 7 },
    metadata: {
      concept: "A very long recursive phrase can blend flat motion, rotation, and height into one helix",
      designerNotes:
        "Each repeat starts on a target and ends on a target, but the middle of the sentence mixes three different movement ideas.",
      idealSolutionLength: 7,
    },
  },
  {
    id: "world-07-level-02",
    name: "Ridge Pivot",
    world: "world-07-very-hard",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { x: 2, y: 0, z: 1, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: -1, z: 1, kind: "TARGET" },
      { x: 2, y: -2, z: 1, kind: "NORMAL" },
      { x: 2, y: -3, z: 0, kind: "NORMAL" },
      { id: "goal-3", x: 1, y: -3, z: 0, kind: "TARGET" },
      { x: 0, y: -3, z: 0, kind: "NORMAL" },
      { x: -1, y: -3, z: 1, kind: "NORMAL" },
      { id: "goal-4", x: -1, y: -2, z: 1, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_LEFT", "JUMP", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 1, p1: 2, p2: 5 },
    stars: { one: 10, two: 9, three: 8 },
    metadata: {
      concept: "Mutual recursion can carry a terrain rhythm through a pivoting route",
      designerNotes:
        "The climb and drop happen inside the transport routine. The activation routine should stay tiny.",
      idealSolutionLength: 8,
    },
  },
  {
    id: "world-07-level-03",
    name: "Helper Spiral",
    world: "world-07-very-hard",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: -1, z: 1, kind: "NORMAL" },
      { id: "goal-2", x: 1, y: -2, z: 1, kind: "TARGET" },
      { x: 1, y: -3, z: 1, kind: "NORMAL" },
      { x: 0, y: -3, z: 2, kind: "NORMAL" },
      { id: "goal-3", x: -1, y: -3, z: 2, kind: "TARGET" },
      { x: -2, y: -3, z: 2, kind: "NORMAL" },
      { x: -2, y: -2, z: 3, kind: "NORMAL" },
      { id: "goal-4", x: -2, y: -1, z: 3, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_LEFT", "JUMP", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 1, p1: 2, p2: 5 },
    stars: { one: 10, two: 9, three: 8 },
    metadata: {
      concept: "A helper routine can hold the bend-and-jump while the recursive routine owns the full sentence",
      designerNotes:
        "This is harder than a flat spiral because the helper must preserve both the new facing and the new height.",
      idealSolutionLength: 8,
    },
  },
  {
    id: "world-07-level-04",
    name: "Pulse Bridge",
    world: "world-07-very-hard",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 0, z: 0, kind: "TARGET" },
      { x: 2, y: 1, z: 1, kind: "NORMAL" },
      { x: 2, y: 2, z: 1, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: 3, z: 1, kind: "TARGET" },
      { x: 1, y: 3, z: 0, kind: "NORMAL" },
      { x: 0, y: 3, z: 0, kind: "NORMAL" },
      { id: "goal-3", x: -1, y: 3, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_RIGHT", "JUMP", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 4, p1: 2, p2: 4 },
    stars: { one: 12, two: 11, three: 10 },
    metadata: {
      concept: "Very hard macro puzzles can still come from pure composition without recursion",
      designerNotes:
        "One helper is just distance. The other helper is the pulse: reach a lamp, light it, rotate, and bridge to the next lane.",
      idealSolutionLength: 10,
    },
  },
  {
    id: "world-07-level-05",
    name: "Crown Traverse",
    world: "world-07-very-hard",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 1, y: -1, z: 1, kind: "TARGET" },
      { x: 1, y: -2, z: 1, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: -2, z: 2, kind: "TARGET" },
      { x: 3, y: -2, z: 2, kind: "NORMAL" },
      { id: "goal-3", x: 3, y: -3, z: 3, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_LEFT", "TURN_RIGHT", "JUMP", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 6, p1: 3, p2: 3 },
    stars: { one: 14, two: 13, three: 12 },
    metadata: {
      concept: "Alternating macro choices can encode a route that climbs through different corner types",
      designerNotes:
        "This one is about choosing the right reusable corner for each segment. The helpers are similar enough to confuse you if the decomposition is sloppy.",
      idealSolutionLength: 12,
    },
  },
];
