import type { LevelDefinition } from "@lumaloop/level-schema";

export const world06Hard: LevelDefinition[] = [
  {
    id: "world-06-level-01",
    name: "Windmill Circuit",
    world: "world-06-hard",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { x: 2, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: 1, z: 0, kind: "TARGET" },
      { x: 2, y: 2, z: 0, kind: "NORMAL" },
      { x: 2, y: 3, z: 0, kind: "NORMAL" },
      { id: "goal-3", x: 1, y: 3, z: 0, kind: "TARGET" },
      { x: 0, y: 3, z: 0, kind: "NORMAL" },
      { x: -1, y: 3, z: 0, kind: "NORMAL" },
      { id: "goal-4", x: -1, y: 2, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_RIGHT", "ACTIVATE", "CALL_P1"],
    slotLimits: { main: 1, p1: 6 },
    stars: { one: 9, two: 8, three: 7 },
    metadata: {
      concept: "A longer corner pattern can still collapse into one recursive phrase",
      designerNotes:
        "The repeated unit is not a single corner. It is a straight stretch, then a bend, then the next target.",
      idealSolutionLength: 7,
    },
  },
  {
    id: "world-06-level-02",
    name: "Spiral Steps",
    world: "world-06-hard",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { x: 1, y: 0, z: 1, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: 0, z: 1, kind: "TARGET" },
      { x: 2, y: -1, z: 2, kind: "NORMAL" },
      { id: "goal-3", x: 2, y: -2, z: 2, kind: "TARGET" },
      { x: 1, y: -2, z: 3, kind: "NORMAL" },
      { id: "goal-4", x: 0, y: -2, z: 3, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["JUMP", "FORWARD", "TURN_LEFT", "ACTIVATE", "CALL_P1"],
    slotLimits: { main: 1, p1: 5 },
    stars: { one: 8, two: 7, three: 6 },
    metadata: {
      concept: "Recursion can encode a spiral climb when each repeat ends on a new ledge",
      designerNotes:
        "Treat each target as the start of the same climbing sentence, not as a special case.",
      idealSolutionLength: 6,
    },
  },
  {
    id: "world-06-level-03",
    name: "Hook Array",
    world: "world-06-hard",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { x: 2, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: -1, z: 0, kind: "TARGET" },
      { x: 2, y: -2, z: 0, kind: "NORMAL" },
      { x: 2, y: -3, z: 0, kind: "NORMAL" },
      { id: "goal-3", x: 1, y: -3, z: 0, kind: "TARGET" },
      { x: 0, y: -3, z: 0, kind: "NORMAL" },
      { x: -1, y: -3, z: 0, kind: "NORMAL" },
      { id: "goal-4", x: -1, y: -2, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_LEFT", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 1, p1: 2, p2: 5 },
    stars: { one: 10, two: 9, three: 8 },
    metadata: {
      concept: "Mutual recursion can split a long repeated hook into activation and repositioning jobs",
      designerNotes:
        "One routine should own the lamp. The other should own the long bend that carries you to the next one.",
      idealSolutionLength: 8,
    },
  },
  {
    id: "world-06-level-04",
    name: "Corner Lift",
    world: "world-06-hard",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 1, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 0, z: 1, kind: "TARGET" },
      { x: 2, y: 1, z: 2, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: 2, z: 2, kind: "TARGET" },
      { x: 1, y: 2, z: 3, kind: "NORMAL" },
      { id: "goal-3", x: 0, y: 2, z: 3, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["JUMP", "FORWARD", "TURN_RIGHT", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 4, p1: 2, p2: 3 },
    stars: { one: 11, two: 10, three: 9 },
    metadata: {
      concept: "Nested procedures can separate a reusable lift from the corner that re-aims it",
      designerNotes:
        "The reusable chunk is the climb itself. The wrapper routine should decide when to light and when to rotate.",
      idealSolutionLength: 9,
    },
  },
  {
    id: "world-06-level-05",
    name: "Lantern Ladder",
    world: "world-06-hard",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { x: 1, y: 0, z: 1, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: 0, z: 1, kind: "TARGET" },
      { x: 2, y: 1, z: 0, kind: "NORMAL" },
      { id: "goal-3", x: 2, y: 2, z: 0, kind: "TARGET" },
      { x: 1, y: 2, z: 1, kind: "NORMAL" },
      { id: "goal-4", x: 0, y: 2, z: 1, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["JUMP", "FORWARD", "TURN_RIGHT", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 1, p1: 2, p2: 4 },
    stars: { one: 9, two: 8, three: 7 },
    metadata: {
      concept: "Mutual recursion can preserve an alternating up-down height rhythm across turns",
      designerNotes:
        "The trick is to notice that the terrain alternates, but the sentence you say about each lamp does not.",
      idealSolutionLength: 7,
    },
  },
];
