import type { LevelDefinition } from "@lumaloop/level-schema";

export const world08Mastery: LevelDefinition[] = [
  {
    id: "world-08-level-01",
    name: "Folded Gallery",
    world: "world-08-mastery",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 0, z: 0, kind: "TARGET" },
      { x: 2, y: 1, z: 0, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: 2, z: 0, kind: "TARGET" },
      { x: 1, y: 2, z: 0, kind: "NORMAL" },
      { id: "goal-3", x: 0, y: 2, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_RIGHT", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 4, p1: 2, p2: 3 },
    stars: { one: 11, two: 10, three: 9 },
    metadata: {
      concept: "A hard route can still collapse when one helper owns distance and another owns the bend",
      designerNotes:
        "The puzzle looks like a path with three lamps, but the real repeated object is a straight segment followed by a quarter turn.",
      idealSolutionLength: 9,
    },
  },
  {
    id: "world-08-level-02",
    name: "Terrace Fold",
    world: "world-08-mastery",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 1, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 0, z: 1, kind: "TARGET" },
      { x: 2, y: -1, z: 2, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: -2, z: 2, kind: "TARGET" },
      { x: 1, y: -2, z: 3, kind: "NORMAL" },
      { id: "goal-3", x: 0, y: -2, z: 3, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["JUMP", "FORWARD", "TURN_LEFT", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 4, p1: 2, p2: 3 },
    stars: { one: 11, two: 10, three: 9 },
    metadata: {
      concept: "The same two-layer abstraction works even when each straight segment is really a climb",
      designerNotes:
        "Do not solve this as three separate ledges. Build one helper for the lift and one helper for the reorientation.",
      idealSolutionLength: 9,
    },
  },
  {
    id: "world-08-level-03",
    name: "Loop Seal",
    world: "world-08-mastery",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-2", x: 1, y: 1, z: 0, kind: "TARGET" },
      { x: 1, y: 2, z: 0, kind: "NORMAL" },
      { id: "goal-3", x: 0, y: 2, z: 0, kind: "TARGET" },
      { x: -1, y: 2, z: 0, kind: "NORMAL" },
      { id: "goal-4", x: -1, y: 1, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_RIGHT", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 1, p1: 2, p2: 4 },
    stars: { one: 8, two: 7, three: 7 },
    metadata: {
      concept: "Mutual recursion can carry a turn rhythm around a loop without re-explaining each corner",
      designerNotes:
        "Keep the activation routine tiny. The transport routine is the one that needs to know the shape of the loop.",
      idealSolutionLength: 7,
    },
  },
  {
    id: "world-08-level-04",
    name: "Ash Switchback",
    world: "world-08-mastery",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { x: 1, y: 0, z: 1, kind: "NORMAL" },
      { id: "goal-2", x: 1, y: 1, z: 1, kind: "TARGET" },
      { x: 1, y: 2, z: 0, kind: "NORMAL" },
      { id: "goal-3", x: 0, y: 2, z: 0, kind: "TARGET" },
      { x: -1, y: 2, z: 1, kind: "NORMAL" },
      { id: "goal-4", x: -1, y: 1, z: 1, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["JUMP", "TURN_RIGHT", "FORWARD", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 1, p1: 2, p2: 4 },
    stars: { one: 8, two: 7, three: 7 },
    metadata: {
      concept: "Recursion gets harder when the repeating unit alternates between climbing and dropping",
      designerNotes:
        "The board changes height every time, but the sentence about each lamp stays stable if you split it at the right place.",
      idealSolutionLength: 7,
    },
  },
  {
    id: "world-08-level-05",
    name: "Twin Hooks",
    world: "world-08-mastery",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { x: 2, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: -1, z: 0, kind: "TARGET" },
      { x: 2, y: -2, z: 0, kind: "NORMAL" },
      { x: 2, y: -3, z: 0, kind: "NORMAL" },
      { id: "goal-3", x: 1, y: -3, z: 0, kind: "TARGET" },
      { x: 0, y: -3, z: 0, kind: "NORMAL" },
      { x: -1, y: -3, z: 0, kind: "NORMAL" },
      { id: "goal-4", x: -1, y: -2, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_LEFT", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 1, p1: 2, p2: 5 },
    stars: { one: 10, two: 9, three: 8 },
    metadata: {
      concept: "A longer hook-shaped relay can still be split cleanly between light and movement",
      designerNotes:
        "The shape is meant to tempt you into programming the whole thing directly. Resist that and isolate the repeated hook.",
      idealSolutionLength: 8,
    },
  },
  {
    id: "world-08-level-06",
    name: "Ridge Hooks",
    world: "world-08-mastery",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { x: 1, y: 0, z: 1, kind: "NORMAL" },
      { x: 2, y: 0, z: 1, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: -1, z: 1, kind: "TARGET" },
      { x: 2, y: -2, z: 0, kind: "NORMAL" },
      { x: 2, y: -3, z: 0, kind: "NORMAL" },
      { id: "goal-3", x: 1, y: -3, z: 0, kind: "TARGET" },
      { x: 0, y: -3, z: 1, kind: "NORMAL" },
      { x: -1, y: -3, z: 1, kind: "NORMAL" },
      { id: "goal-4", x: -1, y: -2, z: 1, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["JUMP", "FORWARD", "TURN_LEFT", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 1, p1: 2, p2: 5 },
    stars: { one: 10, two: 9, three: 8 },
    metadata: {
      concept: "The same hook pattern becomes much harder once height changes are folded into the transport routine",
      designerNotes:
        "The recursive split is still the answer, but now the transport routine has to encode terrain as well as direction.",
      idealSolutionLength: 8,
    },
  },
  {
    id: "world-08-level-07",
    name: "Double Lens",
    world: "world-08-mastery",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { x: 2, y: 0, z: 0, kind: "NORMAL" },
      { x: 2, y: 1, z: 0, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: 2, z: 0, kind: "TARGET" },
      { x: 2, y: 3, z: 0, kind: "NORMAL" },
      { x: 2, y: 4, z: 0, kind: "NORMAL" },
      { x: 1, y: 4, z: 0, kind: "NORMAL" },
      { id: "goal-3", x: 0, y: 4, z: 0, kind: "TARGET" },
      { x: -1, y: 4, z: 0, kind: "NORMAL" },
      { id: "goal-4", x: -2, y: 4, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_RIGHT", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 5, p1: 2, p2: 4 },
    stars: { one: 13, two: 12, three: 11 },
    metadata: {
      concept: "One helper can package a whole lit-and-turn phrase while another helper keeps long distances cheap",
      designerNotes:
        "This level is about deciding which routine owns the activation, not just which routine owns movement.",
      idealSolutionLength: 11,
    },
  },
  {
    id: "world-08-level-08",
    name: "Step Mosaic",
    world: "world-08-mastery",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { x: 1, y: 0, z: 1, kind: "NORMAL" },
      { x: 2, y: 0, z: 1, kind: "NORMAL" },
      { x: 2, y: -1, z: 2, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: -2, z: 2, kind: "TARGET" },
      { x: 2, y: -3, z: 1, kind: "NORMAL" },
      { x: 2, y: -4, z: 1, kind: "NORMAL" },
      { x: 1, y: -4, z: 2, kind: "NORMAL" },
      { id: "goal-3", x: 0, y: -4, z: 2, kind: "TARGET" },
      { x: -1, y: -4, z: 1, kind: "NORMAL" },
      { id: "goal-4", x: -2, y: -4, z: 1, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["JUMP", "FORWARD", "TURN_LEFT", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 5, p1: 2, p2: 4 },
    stars: { one: 13, two: 12, three: 11 },
    metadata: {
      concept: "The same abstract structure can survive a route that rises, turns, descends, and rises again",
      designerNotes:
        "If the level feels like a list of special cases, your decomposition is too concrete.",
      idealSolutionLength: 11,
    },
  },
  {
    id: "world-08-level-09",
    name: "Needle Climb",
    world: "world-08-mastery",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { x: 1, y: 0, z: 1, kind: "NORMAL" },
      { x: 1, y: -1, z: 1, kind: "NORMAL" },
      { id: "goal-2", x: 1, y: -2, z: 2, kind: "TARGET" },
      { x: 1, y: -3, z: 1, kind: "NORMAL" },
      { x: 0, y: -3, z: 1, kind: "NORMAL" },
      { id: "goal-3", x: -1, y: -3, z: 2, kind: "TARGET" },
      { x: -2, y: -3, z: 1, kind: "NORMAL" },
      { x: -2, y: -2, z: 1, kind: "NORMAL" },
      { id: "goal-4", x: -2, y: -1, z: 2, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["JUMP", "TURN_LEFT", "FORWARD", "ACTIVATE", "CALL_P1"],
    slotLimits: { main: 1, p1: 6 },
    stars: { one: 9, two: 8, three: 7 },
    metadata: {
      concept: "A single recursive phrase can still work when each repeat jumps twice and turns in the middle",
      designerNotes:
        "Read the full sentence from one lamp to the next. The middle turn is part of the repeat, not a special exception.",
      idealSolutionLength: 7,
    },
  },
  {
    id: "world-08-level-10",
    name: "Turnstile Crest",
    world: "world-08-mastery",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 1, z: 1, kind: "NORMAL" },
      { id: "goal-2", x: 1, y: 2, z: 1, kind: "TARGET" },
      { x: 1, y: 3, z: 1, kind: "NORMAL" },
      { x: 0, y: 3, z: 2, kind: "NORMAL" },
      { id: "goal-3", x: -1, y: 3, z: 2, kind: "TARGET" },
      { x: -2, y: 3, z: 2, kind: "NORMAL" },
      { x: -2, y: 2, z: 3, kind: "NORMAL" },
      { id: "goal-4", x: -2, y: 1, z: 3, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["TURN_RIGHT", "JUMP", "FORWARD", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 1, p1: 2, p2: 5 },
    stars: { one: 10, two: 9, three: 8 },
    metadata: {
      concept: "A helper can own just the pivot while a recursive routine keeps the full climb moving",
      designerNotes:
        "The smallest routine here is not the whole answer. It is only the hinge that lets the recursive sentence stay compact.",
      idealSolutionLength: 8,
    },
  },
];
