import type { LevelDefinition } from "@lumaloop/level-schema";

export const world03Height: LevelDefinition[] = [
  {
    id: "world-03-level-01",
    name: "First Step Up",
    world: "world-03-height",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 1, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 0, z: 1, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["JUMP", "FORWARD", "ACTIVATE"],
    slotLimits: { main: 3 },
    stars: { one: 5, two: 4, three: 3 },
    metadata: {
      concept: "Jump is required to climb one level",
      designerNotes: "If a move goes uphill, test height before you test distance.",
      idealSolutionLength: 3,
    },
  },
  {
    id: "world-03-level-02",
    name: "Step Down",
    world: "world-03-height",
    board: [
      { x: 0, y: 0, z: 1, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 0, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 1, facing: "E" },
    allowedCommands: ["JUMP", "FORWARD", "ACTIVATE"],
    slotLimits: { main: 3 },
    stars: { one: 5, two: 4, three: 3 },
    metadata: {
      concept: "Jump also handles descending moves",
      designerNotes: "Going down still uses the height-change rule.",
      idealSolutionLength: 3,
    },
  },
  {
    id: "world-03-level-03",
    name: "Plateau Bend",
    world: "world-03-height",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 1, kind: "NORMAL" },
      { x: 2, y: 0, z: 1, kind: "NORMAL" },
      { x: 2, y: 1, z: 1, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 2, z: 1, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["JUMP", "FORWARD", "TURN_RIGHT", "ACTIVATE"],
    slotLimits: { main: 6 },
    stars: { one: 8, two: 7, three: 6 },
    metadata: {
      concept: "Combine jump legality with orientation",
      designerNotes: "Only one move changes height here. After that, the puzzle is about facing.",
      idealSolutionLength: 6,
    },
  },
  {
    id: "world-03-level-04",
    name: "Up Then Down",
    world: "world-03-height",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 1, kind: "NORMAL" },
      { x: 2, y: 0, z: 1, kind: "NORMAL" },
      { x: 3, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 4, y: 0, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["JUMP", "FORWARD", "ACTIVATE"],
    slotLimits: { main: 5 },
    stars: { one: 7, two: 6, three: 5 },
    metadata: {
      concept: "Height transitions can happen more than once in one path",
      designerNotes: "You need the same special move on the way up and on the way down.",
      idealSolutionLength: 5,
    },
  },
  {
    id: "world-03-level-05",
    name: "Stair Turn",
    world: "world-03-height",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 1, kind: "NORMAL" },
      { x: 2, y: 0, z: 1, kind: "NORMAL" },
      { x: 2, y: -1, z: 2, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: -2, z: 2, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["JUMP", "FORWARD", "TURN_LEFT", "ACTIVATE"],
    slotLimits: { main: 6 },
    stars: { one: 8, two: 7, three: 6 },
    metadata: {
      concept: "Jump timing changes when a route bends onto another climb",
      designerNotes: "Group the route by whether height changes, not by how the path looks from above.",
      idealSolutionLength: 6,
    },
  },
  {
    id: "world-03-level-06",
    name: "Split Plateau",
    world: "world-03-height",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 1, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 0, z: 1, kind: "TARGET" },
      { x: 2, y: -1, z: 1, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: -2, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["JUMP", "FORWARD", "TURN_LEFT", "ACTIVATE"],
    slotLimits: { main: 7 },
    stars: { one: 9, two: 8, three: 7 },
    metadata: {
      concept: "The same move type can solve ascent and descent in one route",
      designerNotes: "After the first target, think about height before you think about distance.",
      idealSolutionLength: 7,
    },
  },
  {
    id: "world-03-level-07",
    name: "Mountain Switch",
    world: "world-03-height",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 1, kind: "NORMAL" },
      { x: 2, y: 0, z: 1, kind: "NORMAL" },
      { x: 3, y: 0, z: 0, kind: "NORMAL" },
      { x: 3, y: 1, z: 0, kind: "NORMAL" },
      { x: 3, y: 2, z: 1, kind: "NORMAL" },
      { id: "goal-1", x: 4, y: 2, z: 1, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["JUMP", "FORWARD", "TURN_LEFT", "TURN_RIGHT", "ACTIVATE"],
    slotLimits: { main: 9 },
    stars: { one: 11, two: 10, three: 9 },
    metadata: {
      concept: "Read the whole elevation profile instead of treating height as a single obstacle",
      designerNotes: "Read the route as climb, descend, turn, climb.",
      idealSolutionLength: 9,
    },
  },
];
