import type { LevelDefinition } from "@lumaloop/level-schema";

export const world13Landscapes: LevelDefinition[] = [
  {
    id: "world-13-level-01",
    name: "Block Staircase",
    world: "world-13-landscapes",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { x: 2, y: 0, z: 1, kind: "NORMAL" },
      { x: 3, y: 0, z: 1, kind: "NORMAL" },
      { x: 3, y: 1, z: 1, kind: "NORMAL" },
      { id: "goal-2", x: 3, y: 2, z: 2, kind: "TARGET" },
      { x: 4, y: 2, z: 2, kind: "NORMAL" },
      { x: 5, y: 2, z: 3, kind: "NORMAL" },
      { x: 6, y: 2, z: 3, kind: "NORMAL" },
      { x: 6, y: 3, z: 3, kind: "NORMAL" },
      { id: "goal-3", x: 6, y: 4, z: 4, kind: "TARGET" },
      { x: 0, y: 1, z: 0, kind: "NORMAL" },
      { x: 1, y: 1, z: 1, kind: "NORMAL" },
      { x: 2, y: 1, z: 2, kind: "NORMAL" },
      { x: 4, y: 0, z: 2, kind: "NORMAL" },
      { x: 5, y: 0, z: 2, kind: "NORMAL" },
      { x: 4, y: 1, z: 2, kind: "NORMAL" },
      { x: 5, y: 1, z: 3, kind: "NORMAL" },
      { x: 7, y: 2, z: 4, kind: "NORMAL" },
      { x: 7, y: 3, z: 4, kind: "NORMAL" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_LEFT", "TURN_RIGHT", "JUMP", "ACTIVATE", "CALL_P1"],
    slotLimits: { main: 1, p1: 9 },
    stars: { one: 12, two: 11, three: 10 },
    metadata: {
      concept: "A large staircase can hide a repeated climb-turn phrase",
      designerNotes: "The side blocks make the landscape feel large, but the blue route repeats the same movement sentence.",
      idealSolutionLength: 10,
    },
  },
  {
    id: "world-13-level-02",
    name: "Pillar Maze",
    world: "world-13-landscapes",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 1, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 0, z: 1, kind: "TARGET" },
      { x: 2, y: 1, z: 1, kind: "NORMAL" },
      { x: 2, y: 2, z: 2, kind: "NORMAL" },
      { id: "goal-2", x: 3, y: 2, z: 2, kind: "TARGET" },
      { x: 4, y: 2, z: 1, kind: "NORMAL" },
      { x: 4, y: 3, z: 1, kind: "NORMAL" },
      { id: "goal-3", x: 5, y: 3, z: 2, kind: "TARGET" },
      { x: 0, y: 1, z: 2, kind: "NORMAL" },
      { x: 0, y: 2, z: 2, kind: "NORMAL" },
      { x: 1, y: 2, z: 3, kind: "NORMAL" },
      { x: 3, y: 0, z: 3, kind: "NORMAL" },
      { x: 3, y: 1, z: 2, kind: "NORMAL" },
      { x: 4, y: 0, z: 3, kind: "NORMAL" },
      { x: 5, y: 0, z: 2, kind: "NORMAL" },
      { x: 5, y: 1, z: 1, kind: "NORMAL" },
      { x: 1, y: 3, z: 1, kind: "NORMAL" },
      { x: 2, y: 3, z: 2, kind: "NORMAL" },
      { x: 3, y: 3, z: 3, kind: "NORMAL" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_LEFT", "TURN_RIGHT", "JUMP", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 12, p1: 2, p2: 3 },
    stars: { one: 19, two: 18, three: 17 },
    metadata: {
      concept: "A pillar field asks the player to separate climbing, lighting, and re-aiming helpers",
      designerNotes: "Several nearby columns are distractions. The clean route uses a small climb helper and a small corner helper.",
      idealSolutionLength: 17,
    },
  },
  {
    id: "world-13-level-03",
    name: "Twin Peaks",
    world: "world-13-landscapes",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 2, kind: "TARGET" },
      { x: 1, y: 0, z: 1, kind: "NORMAL" },
      { x: 2, y: 0, z: 1, kind: "NORMAL" },
      { x: 2, y: 1, z: 2, kind: "NORMAL" },
      { x: 3, y: 1, z: 2, kind: "NORMAL" },
      { x: 3, y: 2, z: 1, kind: "NORMAL" },
      { x: 4, y: 2, z: 1, kind: "NORMAL" },
      { id: "goal-2", x: 5, y: 2, z: 2, kind: "TARGET" },
      { x: 1, y: 1, z: 2, kind: "NORMAL" },
      { x: 1, y: 2, z: 3, kind: "NORMAL" },
      { x: 2, y: 2, z: 3, kind: "NORMAL" },
      { x: 4, y: 0, z: 3, kind: "NORMAL" },
      { x: 5, y: 0, z: 3, kind: "NORMAL" },
      { x: 5, y: 1, z: 2, kind: "NORMAL" },
    ],
    start: { x: 0, y: 0, z: 2, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_LEFT", "TURN_RIGHT", "JUMP", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 8, p1: 2, p2: 3 },
    stars: { one: 15, two: 14, three: 13 },
    metadata: {
      concept: "A compact mountain crossing mixes descending jumps, flat travel, and re-aiming",
      designerNotes: "The route starts on a peak, drops into a valley, climbs a middle shelf, then drops and climbs again.",
      idealSolutionLength: 13,
    },
  },
  {
    id: "world-13-level-04",
    name: "Checker Plateau",
    world: "world-13-landscapes",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: 0, z: 0, kind: "TARGET" },
      { x: 3, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-3", x: 4, y: 0, z: 0, kind: "TARGET" },
      { x: 4, y: 1, z: 0, kind: "NORMAL" },
      { id: "goal-4", x: 4, y: 2, z: 0, kind: "TARGET" },
      { x: 4, y: 3, z: 0, kind: "NORMAL" },
      { id: "goal-5", x: 4, y: 4, z: 0, kind: "TARGET" },
      { x: 3, y: 4, z: 0, kind: "NORMAL" },
      { id: "goal-6", x: 2, y: 4, z: 0, kind: "TARGET" },
      { x: 1, y: 4, z: 0, kind: "NORMAL" },
      { id: "goal-7", x: 0, y: 4, z: 0, kind: "TARGET" },
      { x: 0, y: 3, z: 0, kind: "NORMAL" },
      { id: "goal-8", x: 0, y: 2, z: 0, kind: "TARGET" },
      { x: 0, y: 1, z: 0, kind: "NORMAL" },
      { x: 2, y: 1, z: 0, kind: "NORMAL" },
      { x: 2, y: 2, z: 0, kind: "NORMAL" },
      { x: 2, y: 3, z: 0, kind: "NORMAL" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_RIGHT", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 5, p1: 3, p2: 3 },
    stars: { one: 13, two: 12, three: 11 },
    metadata: {
      concept: "A flat checker landscape can use one light-and-step helper plus one corner helper",
      designerNotes: "This is closer to a Lightbot-style blue plateau: many targets, simple terrain, and heavy function pressure.",
      idealSolutionLength: 11,
    },
  },
  {
    id: "world-13-level-05",
    name: "High Road Study",
    world: "world-13-landscapes",
    board: [
      { x: -2, y: 0, z: 0, kind: "NORMAL" },
      { x: -1, y: 0, z: 0, kind: "NORMAL" },
      { x: 0, y: 0, z: 1, kind: "NORMAL" },
      { id: "goal-1", x: 1, y: 0, z: 2, kind: "TARGET" },
      { x: 2, y: 0, z: 2, kind: "NORMAL" },
      { id: "goal-2", x: 0, y: 1, z: 1, kind: "TARGET" },
      { x: 1, y: 1, z: 1, kind: "NORMAL" },
      { x: 2, y: 1, z: 1, kind: "NORMAL" },
      { x: 3, y: 1, z: 1, kind: "NORMAL" },
      { x: 4, y: 1, z: 1, kind: "NORMAL" },
      { id: "goal-3", x: 5, y: 1, z: 1, kind: "TARGET" },
      { x: -1, y: -1, z: 0, kind: "NORMAL" },
      { x: 0, y: -1, z: 1, kind: "NORMAL" },
      { x: 1, y: -1, z: 2, kind: "NORMAL" },
      { x: 2, y: -1, z: 2, kind: "NORMAL" },
      { x: 3, y: 0, z: 1, kind: "NORMAL" },
      { x: 4, y: 0, z: 1, kind: "NORMAL" },
      { x: 5, y: 0, z: 1, kind: "NORMAL" },
    ],
    start: { x: -2, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_LEFT", "TURN_RIGHT", "JUMP", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 15, p1: 3, p2: 2 },
    stars: { one: 22, two: 21, three: 20 },
    metadata: {
      concept: "A screenshot-style high road combines a central tower with a raised front walkway",
      designerNotes: "This level closely follows the uploaded Lightbot frame: central high target, front raised path, and far endpoint target.",
      idealSolutionLength: 20,
    },
  },
  {
    id: "world-13-level-06",
    name: "Terrace Switchback",
    world: "world-13-landscapes",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { id: "goal-2", x: 1, y: 0, z: 0, kind: "TARGET" },
      { id: "goal-3", x: 2, y: 0, z: 0, kind: "TARGET" },
      { id: "goal-4", x: 3, y: 0, z: 0, kind: "TARGET" },
      { id: "goal-5", x: 4, y: 0, z: 0, kind: "TARGET" },
      { id: "goal-6", x: 5, y: 0, z: 0, kind: "TARGET" },
      { id: "goal-7", x: 6, y: 0, z: 0, kind: "TARGET" },
      { id: "goal-8", x: 7, y: 0, z: 0, kind: "TARGET" },
      { id: "goal-9", x: 7, y: 1, z: 1, kind: "TARGET" },
      { id: "goal-10", x: 6, y: 1, z: 1, kind: "TARGET" },
      { id: "goal-11", x: 5, y: 1, z: 1, kind: "TARGET" },
      { id: "goal-12", x: 4, y: 1, z: 1, kind: "TARGET" },
      { id: "goal-13", x: 3, y: 1, z: 1, kind: "TARGET" },
      { id: "goal-14", x: 2, y: 1, z: 1, kind: "TARGET" },
      { id: "goal-15", x: 1, y: 1, z: 1, kind: "TARGET" },
      { id: "goal-16", x: 1, y: 2, z: 2, kind: "TARGET" },
      { id: "goal-17", x: 2, y: 2, z: 2, kind: "TARGET" },
      { id: "goal-18", x: 3, y: 2, z: 2, kind: "TARGET" },
      { id: "goal-19", x: 4, y: 2, z: 2, kind: "TARGET" },
      { id: "goal-20", x: 5, y: 2, z: 2, kind: "TARGET" },
      { id: "goal-21", x: 6, y: 2, z: 2, kind: "TARGET" },
      { id: "goal-22", x: 7, y: 2, z: 2, kind: "TARGET" },
      { x: 2, y: 3, z: 3, kind: "NORMAL" },
      { x: 3, y: 3, z: 3, kind: "NORMAL" },
      { x: 4, y: 3, z: 3, kind: "NORMAL" },
      { x: 5, y: 3, z: 3, kind: "NORMAL" },
      { x: 6, y: 3, z: 3, kind: "NORMAL" },
      { x: 7, y: 3, z: 3, kind: "NORMAL" },
      { x: 8, y: 3, z: 3, kind: "NORMAL" },
      { x: 3, y: 4, z: 4, kind: "NORMAL" },
      { x: 4, y: 4, z: 4, kind: "NORMAL" },
      { x: 5, y: 4, z: 4, kind: "NORMAL" },
      { x: 6, y: 4, z: 4, kind: "NORMAL" },
      { x: 7, y: 4, z: 4, kind: "NORMAL" },
      { x: 8, y: 4, z: 4, kind: "NORMAL" },
      { x: 4, y: 5, z: 5, kind: "NORMAL" },
      { x: 5, y: 5, z: 5, kind: "NORMAL" },
      { x: 6, y: 5, z: 5, kind: "NORMAL" },
      { x: 7, y: 5, z: 5, kind: "NORMAL" },
      { x: 8, y: 5, z: 5, kind: "NORMAL" },
      { x: 8, y: 0, z: 1, kind: "NORMAL" },
      { x: 8, y: 1, z: 2, kind: "NORMAL" },
      { x: 8, y: 2, z: 3, kind: "NORMAL" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_LEFT", "TURN_RIGHT", "JUMP", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 16, p1: 2, p2: 3 },
    stars: { one: 23, two: 22, three: 21 },
    metadata: {
      concept: "A wide Lightbot-style terrace turns a long blue route into a compact nested-helper program",
      designerNotes: "This follows the uploaded screenshot's structure: three long blue switchback lanes in front of a large gray stepped mass.",
      idealSolutionLength: 21,
    },
  },
  {
    id: "world-13-level-07",
    name: "Blue Pyramid Spiral",
    world: "world-13-landscapes",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { id: "goal-2", x: 1, y: 0, z: 0, kind: "TARGET" },
      { id: "goal-3", x: 2, y: 0, z: 0, kind: "TARGET" },
      { id: "goal-4", x: 3, y: 0, z: 0, kind: "TARGET" },
      { id: "goal-5", x: 4, y: 0, z: 0, kind: "TARGET" },
      { id: "goal-6", x: 4, y: 1, z: 0, kind: "TARGET" },
      { id: "goal-7", x: 4, y: 2, z: 0, kind: "TARGET" },
      { id: "goal-8", x: 4, y: 3, z: 0, kind: "TARGET" },
      { id: "goal-9", x: 4, y: 4, z: 0, kind: "TARGET" },
      { id: "goal-10", x: 3, y: 4, z: 0, kind: "TARGET" },
      { id: "goal-11", x: 2, y: 4, z: 0, kind: "TARGET" },
      { id: "goal-12", x: 1, y: 4, z: 0, kind: "TARGET" },
      { id: "goal-13", x: 0, y: 4, z: 0, kind: "TARGET" },
      { id: "goal-14", x: 0, y: 3, z: 0, kind: "TARGET" },
      { id: "goal-15", x: 0, y: 2, z: 0, kind: "TARGET" },
      { id: "goal-16", x: 0, y: 1, z: 0, kind: "TARGET" },
      { id: "goal-17", x: 1, y: 1, z: 1, kind: "TARGET" },
      { id: "goal-18", x: 2, y: 1, z: 1, kind: "TARGET" },
      { id: "goal-19", x: 3, y: 1, z: 1, kind: "TARGET" },
      { id: "goal-20", x: 3, y: 2, z: 1, kind: "TARGET" },
      { id: "goal-21", x: 3, y: 3, z: 1, kind: "TARGET" },
      { id: "goal-22", x: 2, y: 3, z: 1, kind: "TARGET" },
      { id: "goal-23", x: 1, y: 3, z: 1, kind: "TARGET" },
      { id: "goal-24", x: 1, y: 2, z: 1, kind: "TARGET" },
      { id: "goal-25", x: 2, y: 2, z: 2, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_LEFT", "TURN_RIGHT", "JUMP", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 17, p1: 5, p2: 5 },
    stars: { one: 29, two: 28, three: 27 },
    metadata: {
      concept: "Every pyramid tile is activable, forcing the player to manage ring turns and inward stair climbs",
      designerNotes: "This mirrors the uploaded all-blue stair idea as a 5x5, 3x3, 1 stepped pyramid spiral, with helpers for short and long side turns.",
      idealSolutionLength: 27,
    },
  },
];
