import type { LevelDefinition } from "@lumaloop/level-schema";

export const world01Basics: LevelDefinition[] = [
  {
    id: "world-01-level-01",
    name: "First Spark",
    world: "world-01-basics",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 1, y: 0, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "ACTIVATE"],
    slotLimits: { main: 2 },
    stars: { one: 4, two: 3, three: 2 },
    metadata: {
      concept: "Move, then light the target",
      designerNotes: "Start with an immediate win: one move and one activation.",
      idealSolutionLength: 2,
    },
  },
  {
    id: "world-01-level-02",
    name: "Face The Spark",
    world: "world-01-basics",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 0, y: 1, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["TURN_RIGHT", "FORWARD", "ACTIVATE"],
    slotLimits: { main: 3 },
    stars: { one: 5, two: 4, three: 3 },
    metadata: {
      concept: "Turn before moving when the target is not ahead",
      designerNotes: "The first useful action changes direction, not position.",
      idealSolutionLength: 3,
    },
  },
  {
    id: "world-01-level-03",
    name: "Corner Spark",
    world: "world-01-basics",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { x: 2, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 1, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_RIGHT", "ACTIVATE"],
    slotLimits: { main: 5 },
    stars: { one: 7, two: 6, three: 5 },
    metadata: {
      concept: "Execution order matters around a corner",
      designerNotes: "The corner belongs after the straight stretch, not before it.",
      idealSolutionLength: 5,
    },
  },
  {
    id: "world-01-level-04",
    name: "Two Sparks",
    world: "world-01-basics",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 0, z: 0, kind: "TARGET" },
      { x: 2, y: 1, z: 0, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: 2, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_RIGHT", "ACTIVATE"],
    slotLimits: { main: 7 },
    stars: { one: 9, two: 8, three: 7 },
    metadata: {
      concept: "The run is incomplete until every target is lit",
      designerNotes: "Reaching the first lamp is only the midpoint. Keep planning until both targets glow.",
      idealSolutionLength: 7,
    },
  },
  {
    id: "world-01-level-05",
    name: "Twin March",
    world: "world-01-basics",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { x: 2, y: 0, z: 0, kind: "NORMAL" },
      { x: 3, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 4, y: 0, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "ACTIVATE", "CALL_P1"],
    slotLimits: { main: 3, p1: 2 },
    stars: { one: 7, two: 6, three: 5 },
    metadata: {
      concept: "Use Process 1 to reuse a repeated walk",
      designerNotes: "The route is longer than the main routine. Store the repeated two-step walk in Process 1.",
      idealSolutionLength: 5,
    },
  },
  {
    id: "world-01-level-06",
    name: "Signal Line",
    world: "world-01-basics",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { id: "goal-2", x: 1, y: 0, z: 0, kind: "TARGET" },
      { id: "goal-3", x: 2, y: 0, z: 0, kind: "TARGET" },
      { id: "goal-4", x: 3, y: 0, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "ACTIVATE", "CALL_P1"],
    slotLimits: { main: 4, p1: 2 },
    stars: { one: 8, two: 7, three: 6 },
    metadata: {
      concept: "A process can package a repeated action pair",
      designerNotes: "The repeated idea is light-then-step, not just movement.",
      idealSolutionLength: 6,
    },
  },
  {
    id: "world-01-level-07",
    name: "Corner Echo",
    world: "world-01-basics",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 0, z: 0, kind: "TARGET" },
      { x: 2, y: 1, z: 0, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: 2, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_RIGHT", "ACTIVATE", "CALL_P1"],
    slotLimits: { main: 3, p1: 3 },
    stars: { one: 8, two: 7, three: 6 },
    metadata: {
      concept: "Reuse the same process after changing direction",
      designerNotes: "Build one reach-and-light phrase, then aim the robot and use it again.",
      idealSolutionLength: 6,
    },
  },
  {
    id: "world-01-level-08",
    name: "Jump Echo",
    world: "world-01-basics",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 1, y: 0, z: 1, kind: "TARGET" },
      { x: 2, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-2", x: 3, y: 0, z: 1, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["JUMP", "ACTIVATE", "CALL_P1"],
    slotLimits: { main: 2, p1: 3 },
    stars: { one: 7, two: 6, three: 5 },
    metadata: {
      concept: "Processes can hide a repeated height rhythm",
      designerNotes: "The repeated phrase is jump, light, drop. The final drop is skipped once the last target lights.",
      idealSolutionLength: 5,
    },
  },
  {
    id: "world-01-level-09",
    name: "Nested Turn",
    world: "world-01-basics",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { x: 2, y: 0, z: 0, kind: "NORMAL" },
      { x: 2, y: 1, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 2, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_RIGHT", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 3, p1: 2, p2: 2 },
    stars: { one: 9, two: 8, three: 7 },
    metadata: {
      concept: "Process 2 can reuse Process 1 inside a larger idea",
      designerNotes: "One helper owns the distance. The second helper turns and reuses that distance.",
      idealSolutionLength: 7,
    },
  },
  {
    id: "world-01-level-10",
    name: "Spiral Sparks",
    world: "world-01-basics",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 0, z: 0, kind: "TARGET" },
      { x: 2, y: -1, z: 0, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: -2, z: 0, kind: "TARGET" },
      { x: 1, y: -2, z: 0, kind: "NORMAL" },
      { id: "goal-3", x: 0, y: -2, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_LEFT", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 4, p1: 2, p2: 3 },
    stars: { one: 11, two: 10, three: 9 },
    metadata: {
      concept: "Plan with reusable chunks instead of writing the full route",
      designerNotes: "Look for the corner-shaped phrase that repeats after each target.",
      idealSolutionLength: 9,
    },
  },
  {
    id: "world-01-level-11",
    name: "Bridge Key",
    world: "world-01-basics",
    board: [
      { x: 0, y: 0, z: 0, kind: "SWITCH", toggleGroup: "amber" },
      { x: 0, y: 1, z: 0, kind: "NORMAL", toggleGroup: "amber", moveTo: { x: 1, y: 0, z: 0 } },
      { id: "goal-1", x: 2, y: 0, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["TOGGLE", "FORWARD", "ACTIVATE"],
    slotLimits: { main: 4 },
    stars: { one: 6, two: 5, three: 4 },
    metadata: {
      concept: "A switch can change the board before the route works",
      designerNotes: "The route is impossible until the switch moves the bridge into the missing space.",
      idealSolutionLength: 4,
    },
  },
];
