import type { LevelDefinition } from "@lumaloop/level-schema";

export const world01Basics: LevelDefinition[] = [
  {
    id: "world-01-level-01",
    name: "Straight Line",
    world: "world-01-basics",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 0, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "ACTIVATE"],
    slotLimits: { main: 3 },
    stars: { one: 5, two: 4, three: 3 },
    metadata: {
      concept: "Sequence and execution order",
      designerNotes: "Count the spaces before the target. This level doesn't need any turning.",
      idealSolutionLength: 3,
    },
  },
  {
    id: "world-01-level-02",
    name: "Face The Lamp",
    world: "world-01-basics",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 0, y: 1, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 0, y: 2, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["TURN_RIGHT", "FORWARD", "ACTIVATE"],
    slotLimits: { main: 4 },
    stars: { one: 6, two: 5, three: 4 },
    metadata: {
      concept: "Rotation changes future movement",
      designerNotes: "Your first useful action changes direction, not position.",
      idealSolutionLength: 4,
    },
  },
  {
    id: "world-01-level-03",
    name: "Right Angle",
    world: "world-01-basics",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { x: 2, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 1, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_RIGHT", "ACTIVATE"],
    slotLimits: { main: 5 },
    stars: { one: 7, two: 6, three: 5 },
    metadata: {
      concept: "Execution order matters around a corner",
      designerNotes: "The corner belongs after the straight stretch, not before it.",
      idealSolutionLength: 5,
    },
  },
  {
    id: "world-01-level-04",
    name: "Two Lamps",
    world: "world-01-basics",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 0, z: 0, kind: "TARGET" },
      { x: 2, y: 1, z: 0, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: 2, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_RIGHT", "ACTIVATE"],
    slotLimits: { main: 7 },
    stars: { one: 9, two: 8, three: 7 },
    metadata: {
      concept: "The run is incomplete until every target is lit",
      designerNotes: "Reaching the first lamp is only the midpoint. Keep planning until both targets glow.",
      idealSolutionLength: 7,
    },
  },
  {
    id: "world-01-level-05",
    name: "Cross Check",
    world: "world-01-basics",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 0, z: 0, kind: "TARGET" },
      { x: 1, y: 1, z: 0, kind: "NORMAL" },
      { x: 2, y: 1, z: 0, kind: "NORMAL" },
      { x: 3, y: 1, z: 0, kind: "NORMAL" },
      { id: "goal-2", x: 4, y: 1, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_LEFT", "TURN_RIGHT", "ACTIVATE"],
    slotLimits: { main: 9 },
    stars: { one: 11, two: 10, three: 9 },
    metadata: {
      concept: "Plan the whole route before the first success",
      designerNotes: "The early branch looks tempting, but the clean solution lights the first target before committing to the turn.",
      idealSolutionLength: 9,
    },
  },
];
