import type { LevelDefinition } from "@lumaloop/level-schema";

export const world10Phantoms: LevelDefinition[] = [
  {
    id: "world-10-level-01",
    name: "Lantern Lattice",
    world: "world-10-phantoms",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { x: 2, y: 0, z: 0, kind: "NORMAL" },
      { x: 2, y: 1, z: 0, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: 2, z: 0, kind: "TARGET" },
      { x: 2, y: 3, z: 0, kind: "NORMAL" },
      { x: 2, y: 4, z: 0, kind: "NORMAL" },
      { x: 1, y: 4, z: 0, kind: "NORMAL" },
      { id: "goal-3", x: 0, y: 4, z: 0, kind: "TARGET" },
      { x: -1, y: 4, z: 0, kind: "NORMAL" },
      { id: "goal-4", x: -2, y: 4, z: 0, kind: "TARGET" },
      { x: 0, y: 1, z: 0, kind: "NORMAL" },
      { x: 1, y: 1, z: 0, kind: "NORMAL" },
      { x: 0, y: 2, z: 0, kind: "NORMAL" },
      { x: 1, y: 2, z: 0, kind: "NORMAL" },
      { x: 0, y: 3, z: 0, kind: "NORMAL" },
      { x: 1, y: 3, z: 0, kind: "NORMAL" },
      { x: 3, y: 2, z: 0, kind: "NORMAL" },
      { x: 3, y: 3, z: 0, kind: "NORMAL" },
      { x: -1, y: 3, z: 0, kind: "NORMAL" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_RIGHT", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 5, p1: 2, p2: 4 },
    stars: { one: 13, two: 12, three: 11 },
    metadata: {
      concept: "A dense walkable grid can still collapse if one process owns the lit-and-turn phrase and another owns distance",
      designerNotes:
        "Several little corridors look useful here. The winning abstraction still packages the lamp moment, not just the longest hallway.",
      idealSolutionLength: 11,
    },
  },
  {
    id: "world-10-level-02",
    name: "Terrace Smoke",
    world: "world-10-phantoms",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { x: 1, y: 0, z: 1, kind: "NORMAL" },
      { x: 2, y: 0, z: 1, kind: "NORMAL" },
      { x: 2, y: -1, z: 2, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: -2, z: 2, kind: "TARGET" },
      { x: 2, y: -3, z: 1, kind: "NORMAL" },
      { x: 2, y: -4, z: 1, kind: "NORMAL" },
      { x: 1, y: -4, z: 2, kind: "NORMAL" },
      { id: "goal-3", x: 0, y: -4, z: 2, kind: "TARGET" },
      { x: -1, y: -4, z: 1, kind: "NORMAL" },
      { id: "goal-4", x: -2, y: -4, z: 1, kind: "TARGET" },
      { x: 0, y: -1, z: 0, kind: "NORMAL" },
      { x: 1, y: -1, z: 1, kind: "NORMAL" },
      { x: 0, y: -2, z: 1, kind: "NORMAL" },
      { x: 1, y: -2, z: 2, kind: "NORMAL" },
      { x: 0, y: -3, z: 1, kind: "NORMAL" },
      { x: 1, y: -3, z: 1, kind: "NORMAL" },
      { x: -1, y: -3, z: 1, kind: "NORMAL" },
      { x: 3, y: -2, z: 2, kind: "NORMAL" },
      { x: 3, y: -3, z: 1, kind: "NORMAL" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["JUMP", "FORWARD", "TURN_LEFT", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 5, p1: 2, p2: 4 },
    stars: { one: 13, two: 12, three: 11 },
    metadata: {
      concept: "Unused ledges are strongest when they mimic the same skyline as the real climb",
      designerNotes:
        "Many terraces are legal here. The right plan survives only if your processes describe the terrain rhythm instead of memorizing local shape.",
      idealSolutionLength: 11,
    },
  },
  {
    id: "world-10-level-03",
    name: "Counterfeit Loop",
    world: "world-10-phantoms",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-2", x: 1, y: 1, z: 0, kind: "TARGET" },
      { x: 1, y: 2, z: 0, kind: "NORMAL" },
      { id: "goal-3", x: 0, y: 2, z: 0, kind: "TARGET" },
      { x: -1, y: 2, z: 0, kind: "NORMAL" },
      { id: "goal-4", x: -1, y: 1, z: 0, kind: "TARGET" },
      { x: 0, y: 1, z: 0, kind: "NORMAL" },
      { x: 2, y: 1, z: 0, kind: "NORMAL" },
      { x: 2, y: 2, z: 0, kind: "NORMAL" },
      { x: 0, y: 3, z: 0, kind: "NORMAL" },
      { x: -1, y: 3, z: 0, kind: "NORMAL" },
      { x: -2, y: 1, z: 0, kind: "NORMAL" },
      { x: -2, y: 2, z: 0, kind: "NORMAL" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_RIGHT", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 1, p1: 2, p2: 4 },
    stars: { one: 8, two: 7, three: 7 },
    metadata: {
      concept: "A loop with extra exits can still be solved by one tiny process and one transport sentence",
      designerNotes:
        "The fake exits are there to make the loop feel richer than it is. Keep the activation process tiny and let the travel process remember the ring.",
      idealSolutionLength: 7,
    },
  },
  {
    id: "world-10-level-04",
    name: "Helix Decoy",
    world: "world-10-phantoms",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 1, z: 1, kind: "NORMAL" },
      { id: "goal-2", x: 1, y: 2, z: 1, kind: "TARGET" },
      { x: 1, y: 3, z: 1, kind: "NORMAL" },
      { x: 0, y: 3, z: 2, kind: "NORMAL" },
      { id: "goal-3", x: -1, y: 3, z: 2, kind: "TARGET" },
      { x: -2, y: 3, z: 2, kind: "NORMAL" },
      { x: -2, y: 2, z: 3, kind: "NORMAL" },
      { id: "goal-4", x: -2, y: 1, z: 3, kind: "TARGET" },
      { x: 2, y: 0, z: 0, kind: "NORMAL" },
      { x: 2, y: 1, z: 1, kind: "NORMAL" },
      { x: 0, y: 2, z: 1, kind: "NORMAL" },
      { x: -1, y: 2, z: 2, kind: "NORMAL" },
      { x: -1, y: 4, z: 2, kind: "NORMAL" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_RIGHT", "JUMP", "ACTIVATE", "CALL_P1"],
    slotLimits: { main: 1, p1: 6 },
    stars: { one: 9, two: 8, three: 7 },
    metadata: {
      concept: "A recursive helix feels much less obvious when nearby ledges suggest alternate climbs that do not repeat cleanly",
      designerNotes:
        "Ignore the local temptations and read one full sentence from lamp to lamp. If the phrase changes, it is not the right repeat.",
      idealSolutionLength: 7,
    },
  },
  {
    id: "world-10-level-05",
    name: "Pivot Garden",
    world: "world-10-phantoms",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 1, z: 1, kind: "NORMAL" },
      { id: "goal-2", x: 1, y: 2, z: 1, kind: "TARGET" },
      { x: 1, y: 3, z: 1, kind: "NORMAL" },
      { x: 0, y: 3, z: 2, kind: "NORMAL" },
      { id: "goal-3", x: -1, y: 3, z: 2, kind: "TARGET" },
      { x: -2, y: 3, z: 2, kind: "NORMAL" },
      { x: -2, y: 2, z: 3, kind: "NORMAL" },
      { id: "goal-4", x: -2, y: 1, z: 3, kind: "TARGET" },
      { x: 0, y: 1, z: 0, kind: "NORMAL" },
      { x: 2, y: 2, z: 1, kind: "NORMAL" },
      { x: -1, y: 4, z: 2, kind: "NORMAL" },
      { x: -3, y: 2, z: 3, kind: "NORMAL" },
      { x: -1, y: 1, z: 2, kind: "NORMAL" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["TURN_RIGHT", "JUMP", "FORWARD", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 1, p1: 2, p2: 5 },
    stars: { one: 10, two: 9, three: 8 },
    metadata: {
      concept: "Sometimes the smallest process should own only the pivot, even when the board offers many plausible landing spots",
      designerNotes:
        "The extra ledges make it feel like the climb changes every time. It does not. The tiny pivot process is still the hinge that keeps the recursive sentence compact.",
      idealSolutionLength: 8,
    },
  },
  {
    id: "world-10-level-06",
    name: "Phantom Arcade",
    world: "world-10-phantoms",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { x: 2, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: -1, z: 0, kind: "TARGET" },
      { x: 2, y: -2, z: 0, kind: "NORMAL" },
      { x: 2, y: -3, z: 0, kind: "NORMAL" },
      { id: "goal-3", x: 1, y: -3, z: 0, kind: "TARGET" },
      { x: 0, y: -3, z: 0, kind: "NORMAL" },
      { x: -1, y: -3, z: 0, kind: "NORMAL" },
      { id: "goal-4", x: -1, y: -2, z: 0, kind: "TARGET" },
      { x: 1, y: 1, z: 0, kind: "NORMAL" },
      { x: 2, y: 1, z: 0, kind: "NORMAL" },
      { x: 3, y: 0, z: 0, kind: "NORMAL" },
      { x: 4, y: 0, z: 0, kind: "NORMAL" },
      { x: 3, y: -1, z: 0, kind: "NORMAL" },
      { x: 1, y: -1, z: 0, kind: "NORMAL" },
      { x: 0, y: -1, z: 0, kind: "NORMAL" },
      { x: -1, y: -1, z: 0, kind: "NORMAL" },
      { x: -2, y: -1, z: 0, kind: "NORMAL" },
      { x: -2, y: -2, z: 0, kind: "NORMAL" },
      { x: -2, y: -3, z: 0, kind: "NORMAL" },
      { x: 0, y: -2, z: 0, kind: "NORMAL" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_LEFT", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 1, p1: 2, p2: 5 },
    stars: { one: 10, two: 9, three: 8 },
    metadata: {
      concept: "The right hook still wins even when the board offers enough side corridors to hide it in noise",
      designerNotes:
        "Several aisles look like they deserve their own helper. They do not. The clean abstraction is still the same hook sentence repeated from lamp to lamp.",
      idealSolutionLength: 8,
    },
  },
  {
    id: "world-10-level-07",
    name: "Specter Ridge",
    world: "world-10-phantoms",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { x: 1, y: 0, z: 1, kind: "NORMAL" },
      { x: 2, y: 0, z: 1, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: -1, z: 1, kind: "TARGET" },
      { x: 2, y: -2, z: 0, kind: "NORMAL" },
      { x: 2, y: -3, z: 0, kind: "NORMAL" },
      { id: "goal-3", x: 1, y: -3, z: 0, kind: "TARGET" },
      { x: 0, y: -3, z: 1, kind: "NORMAL" },
      { x: -1, y: -3, z: 1, kind: "NORMAL" },
      { id: "goal-4", x: -1, y: -2, z: 1, kind: "TARGET" },
      { x: 0, y: -1, z: 0, kind: "NORMAL" },
      { x: 1, y: -1, z: 1, kind: "NORMAL" },
      { x: 1, y: -2, z: 1, kind: "NORMAL" },
      { x: 3, y: 0, z: 1, kind: "NORMAL" },
      { x: 3, y: -1, z: 1, kind: "NORMAL" },
      { x: 0, y: -2, z: 0, kind: "NORMAL" },
      { x: -1, y: -1, z: 1, kind: "NORMAL" },
      { x: -2, y: -2, z: 1, kind: "NORMAL" },
      { x: -2, y: -3, z: 1, kind: "NORMAL" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["JUMP", "FORWARD", "TURN_LEFT", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 1, p1: 2, p2: 5 },
    stars: { one: 10, two: 9, three: 8 },
    metadata: {
      concept: "Terrain noise is hardest when the fake ledges preserve the same skyline as the real hook",
      designerNotes:
        "Ignore the silhouette and read the motion sentence. The correct recursion still alternates jump, stride, turn, stride in one stable phrase.",
      idealSolutionLength: 8,
    },
  },
  {
    id: "world-10-level-08",
    name: "Ghost Switchyard",
    world: "world-10-phantoms",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { x: 2, y: 0, z: 0, kind: "NORMAL" },
      { x: 2, y: 1, z: 0, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: 2, z: 0, kind: "TARGET" },
      { x: 2, y: 3, z: 0, kind: "NORMAL" },
      { x: 2, y: 4, z: 0, kind: "NORMAL" },
      { x: 1, y: 4, z: 0, kind: "NORMAL" },
      { id: "goal-3", x: 0, y: 4, z: 0, kind: "TARGET" },
      { x: -1, y: 4, z: 0, kind: "NORMAL" },
      { id: "goal-4", x: -2, y: 4, z: 0, kind: "TARGET" },
      { x: 0, y: 1, z: 0, kind: "NORMAL" },
      { x: 1, y: 1, z: 0, kind: "NORMAL" },
      { x: 0, y: 2, z: 0, kind: "NORMAL" },
      { x: 1, y: 2, z: 0, kind: "NORMAL" },
      { x: 0, y: 3, z: 0, kind: "NORMAL" },
      { x: 1, y: 3, z: 0, kind: "NORMAL" },
      { x: 3, y: 1, z: 0, kind: "NORMAL" },
      { x: 3, y: 2, z: 0, kind: "NORMAL" },
      { x: 3, y: 3, z: 0, kind: "NORMAL" },
      { x: -1, y: 3, z: 0, kind: "NORMAL" },
      { x: -2, y: 3, z: 0, kind: "NORMAL" },
      { x: -1, y: 5, z: 0, kind: "NORMAL" },
      { x: 0, y: 5, z: 0, kind: "NORMAL" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_RIGHT", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 5, p1: 2, p2: 4 },
    stars: { one: 13, two: 12, three: 11 },
    metadata: {
      concept: "Dense false corridors make macro decomposition feel less obvious even when the same two helpers still solve everything",
      designerNotes:
        "The center grid is there to waste your attention. The right split still packages distance in one helper and the lamp-turn phrase in the other.",
      idealSolutionLength: 11,
    },
  },
];
