import type { LevelDefinition } from "@lumaloop/level-schema";

export const world02Orientation: LevelDefinition[] = [
  {
    id: "world-02-level-01",
    name: "Zig Corridor",
    world: "world-02-orientation",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 1, z: 0, kind: "NORMAL" },
      { x: 2, y: 1, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 2, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_LEFT", "TURN_RIGHT", "ACTIVATE"],
    slotLimits: { main: 8 },
    stars: { one: 10, two: 9, three: 8 },
    metadata: {
      concept: "Path planning with alternating turns",
      designerNotes: "Plan the whole zigzag before placing the first turn.",
      idealSolutionLength: 8,
    },
  },
  {
    id: "world-02-level-02",
    name: "False Branch",
    world: "world-02-orientation",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { x: 2, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 1, z: 0, kind: "NORMAL" },
      { x: 2, y: -1, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 3, y: -1, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_LEFT", "TURN_RIGHT", "ACTIVATE"],
    slotLimits: { main: 7 },
    stars: { one: 9, two: 8, three: 7 },
    metadata: {
      concept: "Recognize and avoid the tempting wrong branch",
      designerNotes: "One branch only exists to waste a turn. Watch where each option leaves your facing.",
      idealSolutionLength: 7,
    },
  },
  {
    id: "world-02-level-03",
    name: "Double Corner",
    world: "world-02-orientation",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { x: 2, y: 0, z: 0, kind: "NORMAL" },
      { x: 2, y: 1, z: 0, kind: "NORMAL" },
      { x: 2, y: 2, z: 0, kind: "NORMAL" },
      { x: 3, y: 2, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 4, y: 2, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_LEFT", "TURN_RIGHT", "ACTIVATE"],
    slotLimits: { main: 8 },
    stars: { one: 10, two: 9, three: 8 },
    metadata: {
      concept: "Mental simulation over a longer route",
      designerNotes: "Don't solve it corner by corner. Simulate the full route once in your head.",
      idealSolutionLength: 8,
    },
  },
  {
    id: "world-02-level-04",
    name: "Two Lamps",
    world: "world-02-orientation",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 0, z: 0, kind: "TARGET" },
      { x: 2, y: 1, z: 0, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: 2, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_RIGHT", "ACTIVATE"],
    slotLimits: { main: 7 },
    stars: { one: 9, two: 8, three: 7 },
    metadata: {
      concept: "The run is incomplete until every target is lit",
      designerNotes: "Reaching a target is not the same as finishing the run.",
      idealSolutionLength: 7,
    },
  },
  {
    id: "world-02-level-05",
    name: "Detour Lamps",
    world: "world-02-orientation",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 0, z: 0, kind: "TARGET" },
      { x: 2, y: 1, z: 0, kind: "NORMAL" },
      { x: 1, y: 1, z: 0, kind: "NORMAL" },
      { x: 0, y: 1, z: 0, kind: "NORMAL" },
      { id: "goal-2", x: 0, y: 2, z: 0, kind: "TARGET" },
      { x: 1, y: 2, z: 0, kind: "NORMAL" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_LEFT", "TURN_RIGHT", "ACTIVATE"],
    slotLimits: { main: 11 },
    stars: { one: 13, two: 12, three: 11 },
    metadata: {
      concept: "Plan beyond the first success condition",
      designerNotes: "The hard part starts after the first target.",
      idealSolutionLength: 11,
    },
  },
  {
    id: "world-02-level-06",
    name: "Loop Lamps",
    world: "world-02-orientation",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 0, z: 0, kind: "TARGET" },
      { x: 2, y: -1, z: 0, kind: "NORMAL" },
      { x: 2, y: -2, z: 0, kind: "NORMAL" },
      { x: 1, y: -2, z: 0, kind: "NORMAL" },
      { id: "goal-2", x: 0, y: -2, z: 0, kind: "TARGET" },
      { x: 1, y: -1, z: 0, kind: "NORMAL" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_LEFT", "TURN_RIGHT", "ACTIVATE"],
    slotLimits: { main: 10 },
    stars: { one: 12, two: 11, three: 10 },
    metadata: {
      concept: "A route can require different turn directions in the same run",
      designerNotes: "The shortcut looks right because of the shape of the board, not because of your facing.",
      idealSolutionLength: 10,
    },
  },
];
