import type { LevelDefinition } from "@lumaloop/level-schema";

export const world02Orientation: LevelDefinition[] = [
  {
    id: "world-02-level-01",
    name: "Zig Corridor",
    world: "world-02-orientation",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 1, z: 0, kind: "NORMAL" },
      { x: 2, y: 1, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 2, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_LEFT", "TURN_RIGHT", "LIGHT"],
    slotLimits: { main: 8 },
    stars: { one: 10, two: 9, three: 8 },
    metadata: {
      concept: "Path planning with alternating turns",
      designerNotes: "The board is small but punishes shallow simulation.",
      idealSolutionLength: 8,
    },
  },
  {
    id: "world-02-level-02",
    name: "False Branch",
    world: "world-02-orientation",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { x: 2, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 1, z: 0, kind: "NORMAL" },
      { x: 2, y: -1, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 3, y: -1, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_LEFT", "TURN_RIGHT", "LIGHT"],
    slotLimits: { main: 7 },
    stars: { one: 9, two: 8, three: 7 },
    metadata: {
      concept: "Recognize and avoid the tempting wrong branch",
      designerNotes: "One branch exists only to make bad planning legible.",
      idealSolutionLength: 7,
    },
  },
  {
    id: "world-02-level-03",
    name: "Double Corner",
    world: "world-02-orientation",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { x: 2, y: 0, z: 0, kind: "NORMAL" },
      { x: 2, y: 1, z: 0, kind: "NORMAL" },
      { x: 2, y: 2, z: 0, kind: "NORMAL" },
      { x: 3, y: 2, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 4, y: 2, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_LEFT", "TURN_RIGHT", "LIGHT"],
    slotLimits: { main: 8 },
    stars: { one: 10, two: 9, three: 8 },
    metadata: {
      concept: "Mental simulation over a longer route",
      designerNotes: "The path is still linear, but longer enough to force careful sequencing.",
      idealSolutionLength: 8,
    },
  },
  {
    id: "world-02-level-04",
    name: "Two Lamps",
    world: "world-02-orientation",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 0, z: 0, kind: "TARGET" },
      { x: 2, y: 1, z: 0, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: 2, z: 0, kind: "TARGET" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_RIGHT", "LIGHT"],
    slotLimits: { main: 7 },
    stars: { one: 9, two: 8, three: 7 },
    metadata: {
      concept: "The run is incomplete until every target is lit",
      designerNotes: "Players can reach one lamp and still fail, which teaches the completeness condition.",
      idealSolutionLength: 7,
    },
  },
];
