import type { LevelDefinition } from "@lumaloop/level-schema";

export const world09Trickery: LevelDefinition[] = [
  {
    id: "world-09-level-01",
    name: "Mirror Orchard",
    world: "world-09-trickery",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 0, z: 0, kind: "TARGET" },
      { x: 2, y: 1, z: 0, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: 2, z: 0, kind: "TARGET" },
      { x: 1, y: 2, z: 0, kind: "NORMAL" },
      { id: "goal-3", x: 0, y: 2, z: 0, kind: "TARGET" },
      { x: -1, y: 0, z: 0, kind: "NORMAL" },
      { x: -2, y: 0, z: 0, kind: "NORMAL" },
      { x: -1, y: 2, z: 0, kind: "NORMAL" },
      { x: 3, y: 0, z: 0, kind: "NORMAL" },
      { x: 3, y: 1, z: 0, kind: "NORMAL" },
      { x: 3, y: 2, z: 0, kind: "NORMAL" },
      { x: 0, y: 1, z: 0, kind: "NORMAL" },
      { x: 1, y: 1, z: 0, kind: "NORMAL" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_RIGHT", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 4, p1: 2, p2: 3 },
    stars: { one: 11, two: 10, three: 9 },
    metadata: {
      concept: "A mirrored-looking branch can be walkable and still be the wrong abstraction",
      designerNotes:
        "The board offers extra space on both sides, but only one repeating sentence preserves the turn rhythm and fits the slot budget.",
      idealSolutionLength: 9,
    },
  },
  {
    id: "world-09-level-02",
    name: "Hook Bazaar",
    world: "world-09-trickery",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { x: 2, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: -1, z: 0, kind: "TARGET" },
      { x: 2, y: -2, z: 0, kind: "NORMAL" },
      { x: 2, y: -3, z: 0, kind: "NORMAL" },
      { id: "goal-3", x: 1, y: -3, z: 0, kind: "TARGET" },
      { x: 0, y: -3, z: 0, kind: "NORMAL" },
      { x: -1, y: -3, z: 0, kind: "NORMAL" },
      { id: "goal-4", x: -1, y: -2, z: 0, kind: "TARGET" },
      { x: 3, y: 0, z: 0, kind: "NORMAL" },
      { x: 4, y: 0, z: 0, kind: "NORMAL" },
      { x: 3, y: -3, z: 0, kind: "NORMAL" },
      { x: 4, y: -3, z: 0, kind: "NORMAL" },
      { x: 0, y: -1, z: 0, kind: "NORMAL" },
      { x: 0, y: -2, z: 0, kind: "NORMAL" },
      { x: -2, y: -2, z: 0, kind: "NORMAL" },
      { x: -2, y: -1, z: 0, kind: "NORMAL" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_LEFT", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 1, p1: 2, p2: 5 },
    stars: { one: 10, two: 9, three: 8 },
    metadata: {
      concept: "Extra straightaways can tempt you into storing distance instead of the real hook",
      designerNotes:
        "The side aisles are walkable on purpose. The right split is the one that repeats cleanly from lamp to lamp.",
      idealSolutionLength: 8,
    },
  },
  {
    id: "world-09-level-03",
    name: "Terrace Mirage",
    world: "world-09-trickery",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 1, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 0, z: 1, kind: "TARGET" },
      { x: 2, y: -1, z: 2, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: -2, z: 2, kind: "TARGET" },
      { x: 1, y: -2, z: 3, kind: "NORMAL" },
      { id: "goal-3", x: 0, y: -2, z: 3, kind: "TARGET" },
      { x: 0, y: 1, z: 0, kind: "NORMAL" },
      { x: 1, y: 1, z: 0, kind: "NORMAL" },
      { x: 2, y: 1, z: 0, kind: "NORMAL" },
      { x: 3, y: 0, z: 1, kind: "NORMAL" },
      { x: 3, y: -1, z: 1, kind: "NORMAL" },
      { x: 3, y: -2, z: 2, kind: "NORMAL" },
      { x: 1, y: -1, z: 1, kind: "NORMAL" },
      { x: 0, y: -1, z: 1, kind: "NORMAL" },
      { x: -1, y: -2, z: 3, kind: "NORMAL" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["JUMP", "FORWARD", "TURN_LEFT", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 4, p1: 2, p2: 3 },
    stars: { one: 11, two: 10, three: 9 },
    metadata: {
      concept: "Height deception gets sharper when unused terraces look just as inviting as the real climb",
      designerNotes:
        "Read the height rhythm, not the skyline. Several ledges are walkable, but only one three-part sentence compresses the route.",
      idealSolutionLength: 9,
    },
  },
  {
    id: "world-09-level-04",
    name: "Pulse Fork",
    world: "world-09-trickery",
    board: [
      { x: 0, y: 0, z: 0, kind: "NORMAL" },
      { x: 1, y: 0, z: 0, kind: "NORMAL" },
      { id: "goal-1", x: 2, y: 0, z: 0, kind: "TARGET" },
      { x: 2, y: 1, z: 1, kind: "NORMAL" },
      { x: 2, y: 2, z: 1, kind: "NORMAL" },
      { id: "goal-2", x: 2, y: 3, z: 1, kind: "TARGET" },
      { x: 1, y: 3, z: 0, kind: "NORMAL" },
      { x: 0, y: 3, z: 0, kind: "NORMAL" },
      { id: "goal-3", x: -1, y: 3, z: 0, kind: "TARGET" },
      { x: 3, y: 0, z: 0, kind: "NORMAL" },
      { x: 4, y: 0, z: 0, kind: "NORMAL" },
      { x: 3, y: 3, z: 1, kind: "NORMAL" },
      { x: 4, y: 3, z: 1, kind: "NORMAL" },
      { x: -2, y: 3, z: 0, kind: "NORMAL" },
      { x: 0, y: 1, z: 0, kind: "NORMAL" },
      { x: 1, y: 1, z: 0, kind: "NORMAL" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["FORWARD", "TURN_RIGHT", "JUMP", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 4, p1: 2, p2: 4 },
    stars: { one: 12, two: 11, three: 10 },
    metadata: {
      concept: "A forked board can make the wrong helper feel natural even when the right pulse still fits perfectly",
      designerNotes:
        "The long branches are bait. The good split is still a tiny distance helper plus one process that reaches, lights, pivots, and climbs.",
      idealSolutionLength: 10,
    },
  },
  {
    id: "world-09-level-05",
    name: "Switchback Snare",
    world: "world-09-trickery",
    board: [
      { id: "goal-1", x: 0, y: 0, z: 0, kind: "TARGET" },
      { x: 1, y: 0, z: 1, kind: "NORMAL" },
      { id: "goal-2", x: 1, y: 1, z: 1, kind: "TARGET" },
      { x: 1, y: 2, z: 0, kind: "NORMAL" },
      { id: "goal-3", x: 0, y: 2, z: 0, kind: "TARGET" },
      { x: -1, y: 2, z: 1, kind: "NORMAL" },
      { id: "goal-4", x: -1, y: 1, z: 1, kind: "TARGET" },
      { x: 0, y: 1, z: 0, kind: "NORMAL" },
      { x: 0, y: -1, z: 0, kind: "NORMAL" },
      { x: 1, y: -1, z: 1, kind: "NORMAL" },
      { x: 2, y: 1, z: 1, kind: "NORMAL" },
      { x: -2, y: 1, z: 1, kind: "NORMAL" },
      { x: -1, y: 3, z: 1, kind: "NORMAL" },
    ],
    start: { x: 0, y: 0, z: 0, facing: "E" },
    allowedCommands: ["JUMP", "TURN_RIGHT", "FORWARD", "ACTIVATE", "CALL_P1", "CALL_P2"],
    slotLimits: { main: 1, p1: 2, p2: 4 },
    stars: { one: 9, two: 8, three: 7 },
    metadata: {
      concept: "A recursive height pattern gets trickier when extra floor tiles suggest a flatter story than the board really tells",
      designerNotes:
        "The center tiles invite you to think in flat loops. The real repeat is the climb, pivot, and short stride into the next lamp.",
      idealSolutionLength: 7,
    },
  },
];
